#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'nimbro-api','console_scripts','toy_example_4'
__requires__ = 'nimbro-api'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('nimbro-api', 'console_scripts', 'toy_example_4')()
    )
